### ISSUE TITLE
Tracking AMD Work in the ROW

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#160] opened 2019-07-29 17:01 UTC
From Jen
> We’re interested in meeting with you to scope out a project to track where we (AMD) are operating in the right-of-way. A primary motivation is that we are getting a “blanket permit” from ROW division and a condition of that permit is to track where we are operating under that permit. One goal of tracking is to answer questions that the public has about what is going on in a certain location.
>
> I’m thinking about a public-facing map that shows dots and some very simple metadata for where we’ve been over the last 7 (?) days. The map could grab data from our current work order system, as well as data from employees that are not currently tracking their whereabouts (signal timing engineers, communications tech/engineer, construction inspectors). For these employees whose work is not currently tracked, we’d need some very simple form that they could mark their location and a brief description of work. This could be done on tablets or their phones.

**Comment by johnclary** [comment] 2019-07-29 17:02
@amenity please add intake results here.

**Comment by amenity** [comment] 2019-07-30 20:49
Duplicate of https://github.com/cityofaustin/atd-data-tech/issues/413.

**Closed by amenity** 2019-07-30 20:49 UTC
Labels: Service: PM, Type: New Application, Workgroup: AMD
